--항공편
CREATE TABLE FLIGHT(
    NO NUMBER(10) ,
    A_NO NUMBER(10),
    DEPARTURE_DATE DATE NOT NULL,
    DEPARTURE_AIRPORT VARCHAR2(30) NOT NULL,
    ARRIVAL_AIRPORT VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    SEAT VARCHAR2(30) NOT NULL
);
ALTER TABLE FLIGHT ADD CONSTRAINT FLIGHT_NO_PK PRIMARY KEY(NO);
ALTER TABLE FLIGHT ADD CONSTRAINT FLIGHT_A_NO_FK FOREIGN KEY(A_NO) REFERENCES AIRLINE(NO) ON DELETE SET NULL;

--항공사 테이블
CREATE TABLE AIRLINE(
NO NUMBER(10),
NAME VARCHAR2(30) NOT NULL,
ENGLISH_NAME  VARCHAR2(30) NOT NULL,
COUNTRY VARCHAR2(30) NOT NULL,
GRADE VARCHAR2(10)
);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_NO_PK PRIMARY KEY(NO);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_NAME_UK UNIQUE(NAME);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_ENGLISH_NAME_UK UNIQUE(ENGLISH_NAME);
--고객
CREATE TABLE CUSTOMER(
    ID VARCHAR2(20),
    PASSWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PASSPORT_NUMBER VARCHAR2(30) NOT NULL,
    MILEAGE NUMBER(10)
);

ALTER TABLE CUSTOMER ADD CONSTRAINTS CUSTOMER_ID_PK PRIMARY KEY(ID);
ALTER TABLE CUSTOMER ADD CONSTRAINTS CUSTOMER_PASSPORT_NUMBER_UK UNIQUE(PASSPORT_NUMBER);
--예약
DROP TABLE RESERVATION;
CREATE TABLE RESERVATION(
    NO NUMBER(10),
    ID VARCHAR2(20),
    FLIGHT_NO NUMBER(10),
    QUANTITY NUMBER(3) NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_NO_PK PRIMARY KEY(NO);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_CUSTOMER_ID_FK FOREIGN KEY(ID) REFERENCES CUSTOMER(ID) ON DELETE SET NULL;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_FLIGHT_FLIGHT_NO_FK FOREIGN KEY(FLIGHT_NO) REFERENCES FLIGHT(NO) ON DELETE SET NULL;

--AIRLINE_GRADE_FUNC
CREATE OR REPLACE FUNCTION AIRLINE_GRADE_FUNC(VNAME IN AIRLINE.NAME%TYPE)RETURN VARCHAR2
IS
    VNO NUMBER(10);
    VGRADE VARCHAR2(10);
    VMESSAGE VARCHAR2(200);
BEGIN
    SELECT NO,GRADE INTO VNO, VGRADE FROM AIRLINE WHERE NAME = VNAME;
    VMESSAGE := '항공사 번호는 '||VNO||'이고 항공사등급은 '||VGRADE||'입니다.';
    RETURN VMESSAGE;1
END;
/

INSERT INTO AIRLINE VALUES(1, '대한항공','KOREAN AIR','대한민국','1등급');
DELETE FROM AIRLINE WHERE NO =1;
SELECT AIRLINE_GRADE_FUNC('카타르항공') FROM DUAL;

--CUSTOMER 백업 테이블
CREATE TABLE CUSTOMER_RECYCLEBIN(
    NUM NUMBER(3),
    ID VARCHAR2(20),
    PASSWD VARCHAR2(20),
    NAME VARCHAR2(20),
    PASSPORT_NUMBER VARCHAR2(30),
    MILEAGE NUMBER(10)
);
--AIRLINE 백업 테이블
DROP TABLE AIRLINE_RECYCLEBIN;
CREATE TABLE AIRLINE_RECYCLEBIN(
    NUM NUMBER(10),
    NO NUMBER(10),
    NAME VARCHAR2(30) NOT NULL,
    ENGLISH_NAME  VARCHAR2(30) NOT NULL,
    COUNTRY VARCHAR2(30) NOT NULL,
    GRADE VARCHAR2(10)
);
--AIRLINE_RECYCLEBIN 시퀀스
DROP SEQUENCE AIRLINE_RECYCLEBIN_SEQ;
CREATE SEQUENCE AIRLINE_RECYCLEBIN_SEQ
START WITH 1
INCREMENT BY 1;

--AIRLINE DELETE TRIGGER
CREATE OR REPLACE TRIGGER AIRLINE_RECYCLEBIN_TRIGGER
    BEFORE DELETE ON AIRLINE
    FOR EACH ROW
BEGIN
    INSERT INTO AIRLINE_RECYCLEBIN VALUES(AIRLINE_RECYCLEBIN_SEQ.NEXTVAL,:OLD.NO, :OLD.NAME,:OLD.ENGLISH_NAME, :OLD.COUNTRY, :OLD.GRADE);
END;
/


 
--선택한 항공사번호의 FLIGHT의 가격을 10% 인상하는 프로시저
CREATE OR REPLACE PROCEDURE FLIGHT_PRICE_PROC(VANO IN FLIGHT.A_NO%TYPE)
IS
BEGIN
    UPDATE FLIGHT SET PRICE = PRICE * 1.1 WHERE A_NO = VANO;
END;
/
EXECUTE FLIGHT_PRICE_PROC(3);

--FLIGHT  일련번호 시퀀스
CREATE SEQUENCE FLIGHT_NO_SEQ
START WITH 1
INCREMENT BY 1;

--FLIGHT  백업 테이블
CREATE TABLE FLIGHT_RECYCLEBIN(
    NO NUMBER(10) ,
    A_NO NUMBER(10),
    DEPARTURE_DATE DATE,
    DEPARTURE_AIRPORT VARCHAR2(30),
    ARRIVAL_AIRPORT VARCHAR2(30),
    PRICE NUMBER(10),
    SEAT VARCHAR2(30)
);

--FLIGHT  백업 시퀀스
CREATE SEQUENCE FLIGHT_RECYCLEBIN_SEQ
START WITH 1
INCREMENT BY 1;

--FLIGHT  백업 트리거
CREATE OR REPLACE TRIGGER FLIGHT_RECYCLEBIN_TRIGGER
    BEFORE DELETE ON FLIGHT
    FOR EACH ROW
BEGIN
    INSERT INTO FLIGHT_RECYCLEBIN VALUES(FLIGHT_RECYCLEBIN_SEQ.NEXTVAL, :OLD.A_NO, :OLD.DEPARTURE_DATE, :OLD.DEPARTURE_AIRPORT, :OLD.ARRIVAL_AIRPORT, :OLD.PRICE, :OLD.SEAT);
END;
/

UPDATE AIRLINE SET NAME = '아시아나항공', ENGLISH_NAME = 'asiana', COUNTRY = '대한민국' , GRADE = '1등급' WHERE NO = 1;

VARIABLE MESSAGE VARCHAR2(300);

select * from airline;

select * from AIRLINE_RECYCLEBIN;