--항공편
CREATE TABLE FLIGHT(
    NO NUMBER(10) ,
    A_NO NUMBER(10),
    DEPARTURE_DATE DATE NOT NULL,
    DEPARTURE_AIRPORT VARCHAR2(30) NOT NULL,
    ARRIVAL_AIRPORT VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    SEAT VARCHAR2(30) NOT NULL
);
ALTER TABLE FLIGHT ADD CONSTRAINT FLIGHT_NO_PK PRIMARY KEY(NO);
ALTER TABLE FLIGHT ADD CONSTRAINT FLIGHT_A_NO_FK FOREIGN KEY(A_NO) REFERENCES AIRLINE(NO) ON DELETE SET NULL;

--항공사 테이블
CREATE TABLE AIRLINE(
NO NUMBER(10),
NAME VARCHAR2(30) NOT NULL,
ENGLISH_NAME  VARCHAR2(30) NOT NULL,
COUNTRY VARCHAR2(30) NOT NULL,
GRADE VARCHAR2(10)
);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_NO_PK PRIMARY KEY(NO);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_NAME_UK UNIQUE(NAME);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_ENGLISH_NAME_UK UNIQUE(ENGLISH_NAME);
--고객
CREATE TABLE CUSTOMER(
    ID VARCHAR2(20),
    PASSWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PASSPORT_NUMBER VARCHAR2(30) NOT NULL,
    MILEAGE NUMBER(10)
);

ALTER TABLE CUSTOMER ADD CONSTRAINTS CUSTOMER_ID_PK PRIMARY KEY(ID);
ALTER TABLE CUSTOMER ADD CONSTRAINTS CUSTOMER_PASSPORT_NUMBER_UK UNIQUE(PASSPORT_NUMBER);
--예약
DROP TABLE RESERVATION;
CREATE TABLE RESERVATION(
    NO NUMBER(10),
    ID VARCHAR2(20),
    FLIGHT_NO NUMBER(10),
    QUANTITY NUMBER(3) NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_NO_PK PRIMARY KEY(NO);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_CUSTOMER_ID_FK FOREIGN KEY(ID) REFERENCES CUSTOMER(ID) ON DELETE SET NULL;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_FLIGHT_FLIGHT_NO_FK FOREIGN KEY(FLIGHT_NO) REFERENCES FLIGHT(NO) ON DELETE SET NULL;