--순위
--ROWNUM 구하는 순위(공동순위는 없다)
DROP TABLE EMP02;
CREATE TABLE EMP02
AS
SELECT * FROM EMPLOYEES WHERE 1=1;
SELECT ROWNUM, FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM,FIRST_NAME,SALARY FROM (SELECT  FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC);
--공동순위를 구하는 방법 RANK(),DENSE_RANK()
SELECT RANK() OVER(ORDER BY SALARY DESC)AS RANK,FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM,RANK() OVER(ORDER BY SALARY DESC)AS RANK,FIRST_NAME,SALARY
FROM (SELECT  FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;


SELECT ROWNUM,DENSE_RANK() OVER(ORDER BY SALARY DESC)AS DENSE_RANK,FIRST_NAME,SALARY
FROM (SELECT  FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;
--중복없애기
SELECT RANK() OVER(ORDER BY SALARY DESC) AS RANK , DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK 
, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

--부서별 순위 구하기
SELECT DEPARTMENT_ID,RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC,COMMISSION_PCT DESC,DEPARTMENT_ID DESC) AS RANK 
, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY DEPARTMENT_ID,SALARY DESC,COMMISSION_PCT DESC;
--순위구하는 법 비추
SELECT RNUM, FIRST_NAME,SALARY,DEPARTMENT_ID FROM (SELECT ROWNUM AS RNUM, E. * FROM EMPLOYEES E)
WHERE RNUM BETWEEN 101 AND 120;

--순위구하는 방법(강추)
SELECT RNUM, FIRST_NAME,SALARY,DEPARTMENT_ID FROM (SELECT ROWNUM AS RNUM, E. * FROM EMPLOYEES E WHERE ROWNUM <110)
WHERE RNUM >=100;






