--11/25 과제
--구단 선수단 테이블
--방출선수의 테이블 만들기

CREATE TABLE RELEASE(
    NO NUMBER(5),
    NAME VARCHAR(20),
    POSSIT VARCHAR2(2),
    WEEKSAL NUMBER(10)
);
ALTER TABLE RELEASE ADD CONSTRAINT RELEASE_NO_PK PRIMARY KEY(NO);
SELECT * FROM RELEASE;
--트리거
CREATE OR REPLACE TRIGGER TRIGGER_PLAYER
    AFTER DELETE ON PLAYER
    FOR EACH ROW
BEGIN
    INSERT INTO RELEASE VALUES(:OLD.NO,:OLD.NAME,:OLD.POSSIT,:OLD.WEEKSAL);
END;
/
--선수 테이블
CREATE TABLE PLAYER(
    NO NUMBER(5),
    NAME VARCHAR2(20),
    POSSIT VARCHAR2(2),
    WEEKSAL NUMBER(10),
    GAME NUMBER(4)
);
--FA 트리거
CREATE OR REPLACE TRIGGER TRIGGER_RELEASE
    BEFORE DELETE ON RELEASE
    FOR EACH ROW
BEGIN
    INSERT INTO FA(NO,NAME,POSSIT,WEEKSAL) VALUES(:OLD.NO,:OLD.NAME,:OLD.POSSIT,:OLD.WEEKSAL);
END;
/
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_NO_PK PRIMARY KEY(NO);
DROP SEQUENCE PLAYER_NO_SEQ;
CREATE SEQUENCE PLAYER_NO_SEQ
 START WITH 1
 INCREMENT BY 1;

SELECT SUM(WEEKSAL) FROM PLAYER;
INSERT INTO PLAYER VALUES((SELECT NVL(MAX(NO),0)+1 FROM PLAYER),'MESSI','FW','933000',30);
INSERT INTO PLAYER VALUES((SELECT NVL(MAX(NO),0)+1 FROM PLAYER),'LUIZ','DF','203000',23);
INSERT INTO PLAYER VALUES((SELECT NVL(MAX(NO),0)+1 FROM PLAYER),'LEE','GK','3000',40);
SELECT * FROM PLAYER;
COMMIT;
desc player;
--이적시장 테이블
DROP TABLE FA;
CREATE TABLE FA(
 NO NUMBER(5),
    NAME VARCHAR2(20),
    POSSIT VARCHAR2(2),
    WEEKSAL NUMBER(10),
    FEE NUMBER(10),
    PHONE VARCHAR2(13),
    TEAM VARCHAR2(20)
);
ALTER TABLE FA ADD CONSTRAINT FA_NO_PK PRIMARY KEY(NO);

CREATE OR REPLACE FUNCTION PLAYER_FUNCTION(VNO IN PLAYER.NO%TYPE)RETURN VARCHAR2
IS
    
    VWEEKSAL NUMBER(10);
    VMESSAGE VARCHAR2(200);
BEGIN
    SELECT WEEKSAL INTO VWEEKSAL FROM PLAYER WHERE NO = VNO;
    IF( VWEEKSAL >= 1000) THEN
    VMESSAGE := '방출명단 입니다.';
   
    RETURN VMESSAGE;
    ELSE
    VMESSAGE := '방출명단이 아닙니다.';
   
    RETURN VMESSAGE;
    END IF;
END;
/
VARIABLE MESSAGE VARCHAR2(300);
SELECT PLAYER_FUNCTION(3) FROM DUAL; 

CREATE OR REPLACE PROCEDURE PLAYER_PROCEDURE( 
VNO IN PLAYER.NO%TYPE, VGAME PLAYER.GAME%TYPE, VMESSAGE OUT VARCHAR2)
IS
    VPLAYER_RT PLAYER%ROWTYPE;
BEGIN
    UPDATE PLAYER
    SET GAME = GAME + VGAME WHERE NO = VNO;
    COMMIT;
    SELECT * INTO VPLAYER_RT FROM PLAYER WHERE NO = VNO;
    VMESSAGE := VPLAYER_RT.NO||'번 선수가 최근'||VGAME||'경기 출전했습니다';
END;
/
EXECUTE PLAYER_PROCEDURE(1,1,:MESSAGE);
