--PL SQL
--EMPLOYEES에 해당된 이름, 직업, 사원번호를 출력해주는 프로그램을 작성하시오.
DECLARE
 --배열타입정의(테이블타입정의)
   TYPE FIRST_NAME_ARRAY_TYPE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY BINARY_INTEGER;
   TYPE JOB_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.JOB_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE EMPLOYEE_ID_ARRAY_TYPE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;
 --배열타입 변수 선언
    FIRST_NAME_ARRAY FIRST_NAME_ARRAY_TYPE;
    JOB_ID_ARRAY JOB_ID_ARRAY_TYPE;
    EMPLOYEE_ID_ARRAY EMPLOYEE_ID_ARRAY_TYPE;
    ROW_ARRAY EMPLOYEES%ROWTYPE;
    I BINARY_INTEGER := 0;
BEGIN
 --향상된 포문을 통해서 RESULT SET값을 한개씩 가져와서 각 칼럼배열에 저장한다.
    FOR ROW_ARRAY IN (SELECT * FROM EMPLOYEES)LOOP
    I := I + 1;
    FIRST_NAME_ARRAY(I) := ROW_ARRAY.FIRST_NAME;
    JOB_ID_ARRAY(I) := ROW_ARRAY.JOB_ID;
    EMPLOYEE_ID_ARRAY(I) := ROW_ARRAY.EMPLOYEE_ID;

    END LOOP;
--향상된 포문을 이용해서 컬럼 배열값에 저장된 값을 가져와서 출력
    FOR J IN 1..I LOOP
    DBMS_OUTPUT.PUT_LINE(FIRST_NAME_ARRAY(J)||'  /  '||JOB_ID_ARRAY(J)||'  /  '||EMPLOYEE_ID_ARRAY(J));
    END LOOP;
END;
/

--EMPLOYEES에서 'Susan'이름을 갖는 사원의 사원번호, 사원명, 부서번호를 출력
DECLARE
    VEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    VLAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE;

BEGIN
    SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID 
    INTO VEMPLOYEE_ID,VFIRST_NAME,VLAST_NAME,VDEPARTMENT_ID
    FROM EMPLOYEES WHERE FIRST_NAME = 'Susan';
    
    DBMS_OUTPUT.PUT_LINE(VEMPLOYEE_ID||','||VFIRST_NAME||','||VLAST_NAME||','||VDEPARTMENT_ID);
END;
/
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME = 'Susan';











