--STORED PROCEDURE
--부서별로 월급을 인상하는 프로그램. 10번부서는 10%인상, 20번부서 전원 20%, 나머지는 동결
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'EMP01';
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES WHERE 1 =1;
SELECT * FROM EMP01;

CREATE OR REPLACE PROCEDURE EMP01_PROC(VDEPTNO IN EMPLOYEES.DEPARTMENT_ID%TYPE)
IS
BEGIN
    IF VDEPTNO = 10  THEN
        UPDATE EMP01 SET SALARY = SALARY*1.1 WHERE DEPARTMENT_ID = VDEPTNO;
        DBMS_OUTPUT.PUT_LINE(VDEPTNO||'부서는 전원 10% 인상 되었습니다');
    ELSIF VDEPTNO = 20 THEN
        UPDATE EMP01 SET SALARY = SALARY*1.2 WHERE DEPARTMENT_ID = VDEPTNO;
         DBMS_OUTPUT.PUT_LINE(VDEPTNO||'부서는 전원 20% 인상 되었습니다');
    ELSE
         DBMS_OUTPUT.PUT_LINE(VDEPTNO||'부서는 전원동결 되었습니다');
    END IF;

END;
/
EXECUTE EMP01_PROC(30);
--프로시저를 이용해서 사원번호를 입력하면 사원이름, 월급, 직책 매개변수를 통해서 전달
CREATE OR REPLACE PROCEDURE EMP_PROCEDURE_OUTMODE(
    VEMPNO IN EMPLOYEES.EMPLOYEE_ID%TYPE,
    VNAME OUT EMPLOYEES.FIRST_NAME%TYPE,
    VSALARY OUT EMPLOYEES.SALARY%TYPE,
    VJOBID OUT EMPLOYEES.JOB_ID%TYPE
)
IS
    -- 지역변수
BEGIN
    SELECT FIRST_NAME, SALARY, JOB_ID INTO VNAME, VSALARY,VJOBID
    FROM EMPLOYEES WHERE EMPLOYEE_ID = VEMPNO;
END;
/

DECLARE
    VNAME VARCHAR2(100);
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    
BEGIN
    EMP_PROCEDURE_OUTMODE(200,VNAME, VEMP_ROWTYPE.SALARY,VEMP_ROWTYPE.JOB_ID);
    DBMS_OUTPUT.PUT_LINE('이름:'||VNAME);
    DBMS_OUTPUT.PUT_LINE('봉금:'||VEMP_ROWTYPE.SALARY);
    DBMS_OUTPUT.PUT_LINE('직책:'||VEMP_ROWTYPE.JOB_ID);
END;
/
--프로시저를 워크시트에서 불러서 사용하겠다
VARIABLE VNAME VARCHAR2(100)
VARIABLE VSALARY NUMBER
VARIABLE VJOBID VARCHAR2(100)
EXECUTE EMP_PROCEDURE_OUTMODE(300,:VNAME,:VSALARY,:VJOBID);
PRINT VNAME;
PRINT VSALARY;
PRINT VJOBID;

--PROCEDURE IN OUT MODE 동시사용
CREATE OR REPLACE PROCEDURE PROCEDURE_INOUTMODE(VSALARY IN OUT VARCHAR2)
IS
BEGIN
    --VSALARY := TO_CHAR(VSALARY,'$999,999,999,99');
    VSALARY := '$'||SUBSTR(VSALRY,-9,3)||','||SUBSTR(VSALRY,-6,3)||','||SUBSTR(VSALRY,-3,3);
END;
/
DECLARE
   VSALARY VARCHAR2(20) := '123456789';
    --VSALARY := '$'||SUBSTR(VSALRY,-9,3)||','SUBSTR(VSALRY,-6,3)||','SUBSTR(VSALRY,-3,3);
BEGIN
    PROCEDURE_INOUTMODE(VSALARY);
    DBMS_OUTPUT.PUT_LINE('VSALARY='||VSALARY);
END;
/







