--STORED PROCEDURE
--부서별로 월급을 인상하는 프로그램. 10번부서는 10%인상, 20번부서 전원 20%, 나머지는 동결
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'EMP01';
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES WHERE 1 =1;
SELECT * FROM EMP01;

CREATE OR REPLACE PROCEDURE EMP01_PROC(VDEPTNO IN EMPLOYEES.DEPARTMENT_ID%TYPE)
IS
BEGIN
    IF VDEPTNO = 10  THEN
        UPDATE EMP01 SET SALARY = SALARY*1.1 WHERE DEPARTMENT_ID = VDEPTNO;
        DBMS_OUTPUT.PUT_LINE(VDEPTNO||'부서는 전원 10% 인상 되었습니다');
    ELSIF VDEPTNO = 20 THEN
        UPDATE EMP01 SET SALARY = SALARY*1.2 WHERE DEPARTMENT_ID = VDEPTNO;
         DBMS_OUTPUT.PUT_LINE(VDEPTNO||'부서는 전원 20% 인상 되었습니다');
    ELSE
         DBMS_OUTPUT.PUT_LINE(VDEPTNO||'부서는 전원동결 되었습니다');
    END IF;

END;
/
EXECUTE EMP01_PROC(30);