--STORED PROCEDURE
--EMPLOYEES에서 사용자 이름을 패턴으로 검색한뒤 해당되는 사용자정보(사원번호,이름,급여)를 보여주세요
create or replace NONEDITIONABLE PROCEDURE EMP_PROC2(VWORD IN VARCHAR2)
IS

    -- 1문자 변수 선언
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME(VWORD VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%'||VWORD||'%');
BEGIN

    FOR VEMP_ROWTYPE IN  CURSOR_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME|| ' / ' ||VEMP_ROWTYPE.SALARY);

    END LOOP;
END;
/
EXECUTE EMP_PROC2('NA');
--딕셔너리
SELECT * FROM USER_TABLES;
SELECT * FROM user_constraints;
SELECT * FROM USER_CONS_COLUMNS;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_SOURCE;
SELECT * FROM USER_SEQUENCES;