--학과 테이블
CREATE TABLE SUBJECT(
    NUM NUMBER(2),
    NAME VARCHAR2(10)
);
ALTER TABLE SUBJECT ADD CONSTRAINT STU_NUM_FK FOREIGN KEY(NUM) REFERENCES STUDENTS(NUM);

--학생테이블
CREATE TABLE STUDENTS(
    NUM NUMBER(8),
    NAME VARCHAR2(10) NOT NULL,
    ID VARCHAR2(10) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    REGNO NUMBER(13) NOT NULL,
    PHONE NUMBER(11)NOT NULL,
    ADDR VARCHAR2(50)NOT NULL,
    EMAIL VARCHAR2(20)NOT NULL,
    SD_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE STUDENTS ADD CONSTRAINT STU_NUM_PK PRIMARY KEY(NUM);
--과목 테이블
CREATE TABLE LESSON01(
    NUM VARCHAR2(2) NOT NULL,
    NAME VARCHAR2(15) NOT NULL
);
ALTER TABLE LESSON01 ADD CONSTRAINT LESSON01_NUM_PK PRIMARY KEY(NUM);
--수강 테이블
CREATE TABLE TRAINEE(
    STU_NUM NUMBER(2) NOT NULL,
    LESSON01_NUM VARCHAR2(2) NOT NULL,
    SECTION VARCHAR2(10) NOT NULL,
    TR_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_STU_NUM_FK FOREIGN KEY(STU_NUM) REFERENCES STUDENTS(NUM);
ALTER TABLE TRAINEE ADD CONSTRAINT LESSON01_NUM_FK FOREIGN KEY(LESSON01_NUM)REFERENCES LESSON01(NUM);