--PL SQL
--DEPARTMENTS 테이블에 전체내용을 CURSOR 저장하고 FETCH해서 전체정보 출력
DECLARE
    VDEPARTMENTS DEPARTMENTS%ROWTYPE;
    --CURSOR C1 IS SELECT * FROM DEPARTMENTS;
BEGIN
    FOR VDEPARTMENTS IN  (SELECT * FROM DEPARTMENTS) LOOP
    
    DBMS_OUTPUT.PUT_LINE(VDEPARTMENTS.DEPARTMENT_ID ||' / '|| VDEPARTMENTS.DEPARTMENT_NAME);
    
    
    END LOOP;
/*
    OPEN C1;
    LOOP
       FETCH C1 INTO VDEPARTMENTS.DEPARTMENT_ID,VDEPARTMENTS.DEPARTMENT_NAME,VDEPARTMENTS.MANAGER_ID,VDEPARTMENTS.LOCATION_ID;
       EXIT WHEN C1%NOTFOUND;
       DBMS_OUTPUT.PUT_LINE(VDEPARTMENTS.DEPARTMENT_ID||' / '|| VDEPARTMENTS.DEPARTMENT_NAME);

    END LOOP;
    CLOSE C1;
    */
END;
/