--시퀀스 생성
CREATE SEQUENCE EMP_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000
NOCYCLE
CACHE 2;
SELECT * FROM user_sequences;

--EMPLOYEES 구조만 복사 EMP01
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE 1=0;

SELECT * FROM EMP01;
--EMP_SEQ.NEXTVAL
INSERT INTO EMP01 VALUES(EMP_SEQ.NEXTVAL, 'NJH', SYSDATE);


--EMP_SEQ.CURRVAL
SELECT EMP_SEQ.CURRVAL FROM DUAL;


--SEQUENCE DEPT_SEQ 생성하기, 시작값 10,증가치 10, 결과치 30
CREATE SEQUENCE DEPT_SEQ
START WITH 10
INCREMENT BY 10
MAXVALUE 30;

SELECT * FROM user_sequences;

--DEP01 테이블 구조 복사하기
DROP TABLE DEPT01;
CREATE TABLE DEPT01
AS
SELECT DEPARTMENT_ID,DEPARTMENT_NAME, LOCATION_ID FROM departments WHERE 1=0;
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES (DEPT_SEQ.NEXTVAL,'인사과', 1 );
INSERT INTO DEPT01 VALUES (DEPT_SEQ.NEXTVAL,'총무과', 2 );
INSERT INTO DEPT01 VALUES (DEPT_SEQ.NEXTVAL,'서무과', 3 );
INSERT INTO DEPT01 VALUES (DEPT_SEQ.NEXTVAL,'교육과', 4 );

--SEQUENCE 수정하기
ALTER SEQUENCE DEPT_SEQ
MAXVALUE 100;

SELECT * FROM user_sequences;
--SEQUENCE 삭제
DROP SEQUENCE DEPT_SEQ;







