--EMPLOYEES 복사
CREATE TABLE EMP03
AS 
SELECT * FROM EMPLOYEES;
--모든 사원의 부서번호를 30번으로 수정하자
--DELETE  와 UPDATE SET 할때 WHERE 쓰자
SELECT * FROM EMP03;
UPDATE EMP03 SET DEPARTMENT_ID = 30;
ROLLBACK;
--모든사원의 급여를 10% 인상한다.
UPDATE EMP03 SET SALARY = SALARY *1.1;
ROLLBACK;
--입사일을 오늘로 수정한다.
UPDATE EMP03 SET HIRE_DATE = SYSDATE;
--부서번호가 10번인 사원의 부서번호를 30번으로 수정
UPDATE EMP03 SET department_id =30 WHERE department_id = 10;
--급여가 3000만원 이상인 사원만 급여를 10%를 인상
UPDATE EMP03 SET salary = salary * 1.1 WHERE salary >= 3000;
--2007년에 입사한 사원의 입사일을 오늘로 수정
UPDATE EMP03 SET hire_date = SYSDATE WHERE SUBSTR(HIRE_DATE,1,2)='07';
UPDATE EMP03 SET DEPARTMENT_ID = 20, JOB_ID = 'FI_MGR' WHERE UPPER(FIRST_NAME) =UPPER('SUSAN');
SELECT * FROM EMP03 WHERE FIRST_NAME = 'Susan';

UPDATE EMP03 SET SALARY = 17000, COMMISSION_PCT = 0.45 WHERE UPPER(LAST_NAME) = UPPER('RUSSELL');

DELETE FROM EMP03 WHERE department_id=30;
CREATE TABLE MY_CUSTOMER(
    CODE VARCHAR(7),
    name varchar(10) not null,
    gender char(1) not null,
    birthday varchar(8) not null,
    phone varchar(16)
);
alter table MY_customer add CONSTRAINT CODE_PK primary key(CODE);
alter table MY_customer add constraint gender_check check(gender in('M','W'));
alter table MY_customer add CONSTRAINT phone_uk unique(phone);
--값 넣는법
INSERT INTO MY_CUSTOMER  VALUES ('2017108','박승대','M','19711430','010-2580-9919');
INSERT INTO MY_CUSTOMER  VALUES ('2019302','전미래','W','19740812','010-8864-0232');
SELECT * FROM MY_CUSTOMER;

--3개 외우기 제약 조건 검색기능

select * from user_tables;
select * from user_cons_columns;

select * from customer;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_EMAIL_UK;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_GENDER_CHECK;
--MERGE MYCOSTOMER => CUSTOMER 병합을 진행하는 데 없으면 INSERT, 없으면 
MERGE INTO CUSTOMER C
    USING MY_CUSTOMER M
    ON (C.CODE = M.CODE)
    WHEN MATCHED THEN
        UPDATE SET C.NAME = M.NAME, C.GENDER = M.GENDER, C.BIRTHDAY = M.BIRTH, C.PHONE = M.PHONE
    WHEN NOT MATCHED THEN
        INSERT (C.CODE,C.NAME,C.GENDER,C.BIRTH,C.PHONE)VALUES(M.CODE,M.NAME,M.GENDER,M.BIRTH,M.PHONE);
CREATE TABLE DEPARTMENT(
    NO NUMBER(10) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    AREA_NAME VARCHAR(10) NOT NULL
);
ALTER TABLE DEPARTMENT ADD CONSTRAINT NO_PK PRIMARY KEY(NO);
CREATE TABLE EMP(
    NAME VARCHAR2(10) NOT NULL,
    POSIT VARCHAR2(10) NOT NULL,
    SALARY NUMBER(10) NOT NULL,
     NO NUMBER(10)REFERENCES DEPARTMENT(NO)
);
--밑에서 FOREING KEY제약 조건
ALTER TABLE EMP ADD CONSTRAINT EMP_DEPARTMENT_NO_FK FOREIGN KEY(NO) REFERENCES DEPARTMENT(NO);

-------
CREATE TABLE DEPT02(
    DEPT_NO NUMBER,
    DEPT_NAME VARCHAR2(10),
    LOCATION VARCHAR2(10)
);

ALTER TABLE DEPT02 ADD CONSTRAINT DEPT02_NO_PK PRIMARY KEY(DEPT_NO);

CREATE TABLE MEMBER01(
    MEMBER_NO NUMBER,
    MEMBER_NAME VARCHAR(10),
    JOB_ID VARCHAR(10),
    DEPT_NO NUMBER
);

ALTER TABLE MEMBER01 ADD CONSTRAINT MEMBER01_NO_PK PRIMARY KEY(MEMBER_NO);
ALTER TABLE MEMBER01 ADD CONSTRAINT MEMBER01_NO_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPT02(DEPT_NO);


----------------
INSERT INTO DEPT02 VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT02 VALUES(20,'RESEARCH','DALLAS');
INSERT INTO DEPT02 VALUES(30,'SALES','CHICAGO');
INSERT INTO DEPT02 VALUES(40,'OPERATIONS','BOSTON');


INSERT INTO MEMBER01 VALUES(7499,'ALLEN','SALESMAN',30);
INSERT INTO MEMBER01 VALUES(7566,'JONES','MANAGER',40);
SELECT * FROM DEPT02;
SELECT * FROM MEMBER01;

DELETE FROM member01 WHERE DEPT_NO = 40;
DELETE FROM DEPT02 WHERE DEPT_NO = 40;

ALTER TABLE MEMBER01 DROP CONSTRAINT MEMBER01_NO_FK;
ALTER TABLE MEMBER01 ADD CONSTRAINT MEMBER01_NO_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPT02(DEPT_NO) ON DELETE CASCADE;


--문제1번
CREATE TABLE EMPL1(
    NO NUMBER(4),
    NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    MANAGER NUMBER(4),
    HIRE_DATE DATE NOT NULL,
    SALARY NUMBER(7,2) NOT NULL,
    COMMISSION NUMBER(7,2) DEFAULT 0.0,
    DEP_NO NUMBER(2) NOT NULL
);
ALTER TABLE EMPL1 ADD CONSTRAINT EMPL1_NO_PK PRIMARY KEY(NO);
--문제2 값주기
INSERT INTO EMPL1(empl1.no, empl1.NAME,empl1.job,empl1.manager,empl1.hire_date,empl1.salary,empl1.dep_no)
VALUES(7369,'SMITH','CLEAK',7836,'80/12/17',800,20);
INSERT INTO EMPL1 VALUES(7499,'ALLEN','SALESMAN',7369,'87/12/20',1600,300,30);
INSERT INTO EMPL1(empl1.no, empl1.NAME,empl1.job,empl1.hire_date,empl1.salary,empl1.dep_no)
VALUES(7839,'KING','PRESIDENT','81/02/08',5000,10);

--문제3번
CREATE TABLE MEMBERS(
    ID VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    REGNO VARCHAR2(13) NOT NULL,
    PHONE VARCHAR2(13) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL
);
ALTER TABLE MEMBERS ADD CONSTRAINT ID_PK PRIMARY KEY(ID);
INSERT INTO MEMBERS VALUES('ABC','JOHN','123-456','12-34-56','KOREA');
INSERT INTO MEMBERS VALUES('HELLO','PALMER','991117-123456','010-4090-8063','KOREA');
--문제 4번
CREATE TABLE BOOKS(
    CODE NUMBER(4) NOT NULL,
    TITLE VARCHAR2(50) NOT NULL,
    COUNT NUMBER(6) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    PUBLISH VARCHAR2(50) NOT NULL
);
ALTER TABLE BOOKS ADD CONSTRAINT BOOKS_CODE_PK PRIMARY KEY(CODE);
INSERT INTO BOOKS VALUES(1000,'ABC',11,5000,'HELLO');
INSERT INTO BOOKS VALUES(1001,'FOUR FOUR TWO',16,50000,'BBC');


select * from user_tables;
------비디오
--고객
CREATE TABLE CUSTOMER01(
    CUS_CODE NUMBER(5),
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER(3),
    PHONE VARCHAR2(20),
    ADDR VARCHAR2(50)
);
ALTER TABLE CUSTOMER01 ADD CONSTRAINT CUS_CODE_PK PRIMARY KEY(CUS_CODE);
--비디오
CREATE TABLE VIDEO(
    VID_CODE NUMBER(5),
    TITLE VARCHAR2(50) NOT NULL,
    GENRE VARCHAR2(30),
    PAY NUMBER(7) NOT NULL,
    LEND_STATE NUMBER(1),
    MAKE_COMPANY VARCHAR2(50),
    MAKE_DATE DATE,
    VIEW_AGE NUMBER(1)
);
ALTER TABLE VIDEO ADD CONSTRAINT VID_CODE_PK PRIMARY KEY(VID_CODE);
--대여반납
CREATE TABLE LEND_RETUR(
    LR_CODE NUMBER(5),
    CUS_CODE NUMBER(5),
    VID_CODE NUMBER(5),
    LEND_DARE DATE,
    RETURN_DATE DATE,
    LEND_PAY NUMBER(7)
);
ALTER TABLE LEND_RETUR ADD CONSTRAINT LR_CODE_PK PRIMARY KEY(LR_CODE);
ALTER TABLE LEND_RETUR ADD CONSTRAINT CUS_CODE_FK FOREIGN KEY(CUS_CODE) REFERENCES CUSTOMER01(CUS_CODE);
ALTER TABLE LEND_RETUR ADD CONSTRAINT  VID_CODE_FK FOREIGN KEY(VID_CODE) REFERENCES VIDEO(VID_CODE);

