--선수의 테이블 만들기
CREATE TABLE PLAYER(
    NO NUMBER(5),
    NAME VARCHAR2(20),
    POSSIT VARCHAR2(2),
    WEEKSAL NUMBER(10),
    GAME NUMBER(4)
);
ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_NO_PK PRIMARY KEY(NO);
DROP SEQUENCE PLAYER_NO_SEQ;
CREATE SEQUENCE PLAYER_NO_SEQ
 START WITH 1
 INCREMENT BY 1;

SELECT SUM(WEEKSAL) FROM PLAYER;
INSERT INTO PLAYER VALUES((SELECT NVL(MAX(NO),0)+1 FROM PLAYER),'MESSI','FW','933000',30);
INSERT INTO PLAYER VALUES((SELECT NVL(MAX(NO),0)+1 FROM PLAYER),'LUIZ','DF','203000',23);
INSERT INTO PLAYER VALUES((SELECT NVL(MAX(NO),0)+1 FROM PLAYER),'LEE','GK','3000',40);
SELECT * FROM PLAYER;
COMMIT;
desc player;

CREATE OR REPLACE FUNCTION PLAYER_FUNCTION(VNO IN PLAYER.NO%TYPE)RETURN VARCHAR2
IS
    
    VWEEKSAL NUMBER(10);
    VMESSAGE VARCHAR2(200);
BEGIN
    SELECT WEEKSAL INTO VWEEKSAL FROM PLAYER WHERE NO = VNO;
    IF( VWEEKSAL >= 100000) THEN
    VMESSAGE := '샐러리캡 규정 위반입니다';
   
    RETURN VMESSAGE;
    ELSE
    VMESSAGE := '영입 가능합니다.';
   
    RETURN VMESSAGE;
    END IF;
END;
/
VARIABLE MESSAGE VARCHAR2(300);
SELECT PLAYER_FUNCTION(3) FROM DUAL; 

CREATE OR REPLACE PROCEDURE PLAYER_PROCEDURE( 
VNO IN PLAYER.NO%TYPE, VGAME PLAYER.GAME%TYPE, VMESSAGE OUT VARCHAR2)
IS
    VPLAYER_RT PLAYER%ROWTYPE;
BEGIN
    UPDATE PLAYER
    SET GAME = GAME + VGAME WHERE NO = VNO;
    COMMIT;
    SELECT * INTO VPLAYER_RT FROM PLAYER WHERE NO = VNO;
    VMESSAGE := VPLAYER_RT.NO||'번 선수가 최근'||VGAME||'경기 출전했습니다';
END;
/
EXECUTE PLAYER_PROCEDURE(1,1,:MESSAGE);