--Transction
drop TABLE DEP02;

--테이블 복사
CREATE TABLE DEP02
AS
SELECT * FROM DEPARTMENTS WHERE 1=0;

DESC DEP02
SELECT * FROM user_constraints WHERE TABLE_NAME = 'DEP02';

--내용복사
INSERT INTO DEP02 SELECT * FROM DEPARTMENTS;

SELECT * FROM DEP02;

ROLLBACK;