--EMPLOYEES 복사
CREATE TABLE EMP03
AS 
SELECT * FROM EMPLOYEES;
--모든 사원의 부서번호를 30번으로 수정하자
--DELETE  와 UPDATE SET 할때 WHERE 쓰자
SELECT * FROM EMP03;
UPDATE EMP03 SET DEPARTMENT_ID = 30;
ROLLBACK;
--모든사원의 급여를 10% 인상한다.
UPDATE EMP03 SET SALARY = SALARY *1.1;
ROLLBACK;
--입사일을 오늘로 수정한다.
UPDATE EMP03 SET HIRE_DATE = SYSDATE;
--부서번호가 10번인 사원의 부서번호를 30번으로 수정
UPDATE EMP03 SET department_id =30 WHERE department_id = 10;
--급여가 3000만원 이상인 사원만 급여를 10%를 인상
UPDATE EMP03 SET salary = salary * 1.1 WHERE salary >= 3000;
--2007년에 입사한 사원의 입사일을 오늘로 수정
UPDATE EMP03 SET hire_date = SYSDATE WHERE SUBSTR(HIRE_DATE,1,2)='07';
UPDATE EMP03 SET DEPARTMENT_ID = 20, JOB_ID = 'FI_MGR' WHERE UPPER(FIRST_NAME) =UPPER('SUSAN');
SELECT * FROM EMP03 WHERE FIRST_NAME = 'Susan';

UPDATE EMP03 SET SALARY = 17000, COMMISSION_PCT = 0.45 WHERE UPPER(LAST_NAME) = UPPER('RUSSELL');

DELETE FROM EMP03 WHERE department_id=30;
CREATE TABLE MY_CUSTOMER(
    CODE VARCHAR(7),
    name varchar(10) not null,
    gender char(1) not null,
    birthday varchar(8) not null,
    phone varchar(16)
);
alter table MY_customer add CONSTRAINT CODE_PK primary key(CODE);
alter table MY_customer add constraint gender_check check(gender in('M','W'));
alter table MY_customer add CONSTRAINT phone_uk unique(phone);
--값 넣는법
INSERT INTO MY_CUSTOMER  VALUES ('2017108','박승대','M','19711430','010-2580-9919');
INSERT INTO MY_CUSTOMER  VALUES ('2019302','전미래','W','19740812','010-8864-0232');
SELECT * FROM MY_CUSTOMER;

--3개 외우기 제약 조건 검색기능

select * from user_tables;
select * from user_cons_columns;

select * from customer;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_EMAIL_UK;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_GENDER_CHECK;
--MERGE MYCOSTOMER => CUSTOMER 병합을 진행하는 데 없으면 INSERT, 없으면 
MERGE INTO CUSTOMER C
    USING MY_CUSTOMER M
    ON (C.CODE = M.CODE)
    WHEN MATCHED THEN
        UPDATE SET C.NAME = M.NAME, C.GENDER = M.GENDER, C.BIRTHDAY = M.BIRTH, C.PHONE = M.PHONE
    WHEN NOT MATCHED THEN
        INSERT (C.CODE,C.NAME,C.GENDER,C.BIRTH,C.PHONE)VALUES(M.CODE,M.NAME,M.GENDER,M.BIRTH,M.PHONE);
CREATE TABLE DEPARTMENT(
    NO NUMBER(10) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    AREA_NAME VARCHAR(10) NOT NULL
);
ALTER TABLE DEPARTMENT ADD CONSTRAINT NO_PK PRIMARY KEY(NO);
CREATE TABLE EMP(
    NAME VARCHAR2(10) NOT NULL,
    POSIT VARCHAR2(10) NOT NULL,
    SALARY NUMBER(10) NOT NULL,
     NO NUMBER(10)REFERENCES DEPARTMENT(NO)
);
--밑에서 FOREING KEY제약 조건
ALTER TABLE EMP ADD CONSTRAINT EMP_DEPARTMENT_NO_FK FOREIGN KEY(NO) REFERENCES DEPARTMENT(NO);

-------
CREATE TABLE DEPT02(
    DEPT_NO NUMBER,
    DEPT_NAME VARCHAR2(10),
    LOCATION VARCHAR2(10)
);

ALTER TABLE DEPT02 ADD CONSTRAINT DEPT02_NO_PK PRIMARY KEY(DEPT_NO);

CREATE TABLE MEMBER01(
    MEMBER_NO NUMBER,
    MEMBER_NAME VARCHAR(10),
    JOB_ID VARCHAR(10),
    DEPT_NO NUMBER
);

ALTER TABLE MEMBER01 ADD CONSTRAINT MEMBER01_NO_PK PRIMARY KEY(MEMBER_NO);
ALTER TABLE MEMBER01 ADD CONSTRAINT MEMBER01_NO_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPT02(DEPT_NO);


----------------
INSERT INTO DEPT02 VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT02 VALUES(20,'RESEARCH','DALLAS');
INSERT INTO DEPT02 VALUES(30,'SALES','CHICAGO');
INSERT INTO DEPT02 VALUES(40,'OPERATIONS','BOSTON');


INSERT INTO MEMBER01 VALUES(7499,'ALLEN','SALESMAN',30);
INSERT INTO MEMBER01 VALUES(7566,'JONES','MANAGER',40);
SELECT * FROM DEPT02;
SELECT * FROM MEMBER01;

DELETE FROM member01 WHERE DEPT_NO = 40;
DELETE FROM DEPT02 WHERE DEPT_NO = 40;

ALTER TABLE MEMBER01 DROP CONSTRAINT MEMBER01_NO_FK;
ALTER TABLE MEMBER01 ADD CONSTRAINT MEMBER01_NO_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPT02(DEPT_NO) ON DELETE CASCADE;


--










------비디오



