--insert into테이블
create table IT(
    NO1 NUMBER,
    NO2 NUMBER,
    NO3 NUMBER
    
); 
DESC IT;
INSERT INTO IT VALUES(1,2,3);
INSERT INTO IT VALUES(1,2,4);
INSERT INTO IT VALUES(1,2,NULL);
INSERT INTO IT(NO1,NO2) VALUES(11,22);
INSERT INTO IT(NO1,NO2) VALUES(11,'문자');
INSERT INTO IT(NO1,NO2) VALUES(1111);
INSERT INTO IT(NO1,NO2) VALUES(1111,222,3333);
INSERT INTO IT(NO1,NO2) VALUES(1111,222);
INSERT INTO IT VALUES(1111,NULL,333);
SELECT * FROM IT;
DELETE FROM IT WHERE NO3 IS NULL;
ALTER TABLE IT MODIFY NO3 NUMBER NOT NULL;

--DEPT 테이블 생성
CREATE TABLE DEPT
AS 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID FROM DEPARTMENTS;
SELECT * FROM DEPT;
DELETE FROM DEPT;
TRUNCATE TABLE DEPT;
ROLLBACK;
INSERT INTO DEPT SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID FROM DEPARTMENT;


