--항공사 테이블
CREATE TABLE AIRLINE(
    NO NUMBER(10),
    NAME VARCHAR2(30) NOT NULL,
    ENGLISH_NAME  VARCHAR2(30) NOT NULL,
    COUNTRY VARCHAR2(30) NOT NULL,
    GRADE VARCHAR2(10)
);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_NO_PK PRIMARY KEY(NO);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_NAME_UK UNIQUE(NAME);
ALTER TABLE AIRLINE ADD CONSTRAINT AIRLINE_ENGLISH_NAME_UK UNIQUE(ENGLISH_NAME);

--항공사 AIRLINE_GRADE_FUNC
CREATE OR REPLACE FUNCTION AIRLINE_GRADE_FUNC(VNAME IN AIRLINE.NAME%TYPE)RETURN VARCHAR2
IS
    VNO NUMBER(10);
    VGRADE VARCHAR2(10);
    VMESSAGE VARCHAR2(200);
BEGIN
    SELECT NO,GRADE INTO VNO, VGRADE FROM AIRLINE WHERE NAME = VNAME;
    VMESSAGE := '항공사 번호는 '||VNO||'이고 항공사등급은 '||VGRADE||'입니다.';
    RETURN VMESSAGE;1
END;
/

INSERT INTO AIRLINE VALUES(1, '대한항공','KOREAN AIR','대한민국','1등급');
DELETE FROM AIRLINE WHERE NO =1;
SELECT AIRLINE_GRADE_FUNC('카타르항공') FROM DUAL;

--AIRLINE 백업 테이블
DROP TABLE AIRLINE_RECYCLEBIN;
CREATE TABLE AIRLINE_RECYCLEBIN(
    NUM NUMBER(10),
    NO NUMBER(10),
    NAME VARCHAR2(30) NOT NULL,
    ENGLISH_NAME  VARCHAR2(30) NOT NULL,
    COUNTRY VARCHAR2(30) NOT NULL,
    GRADE VARCHAR2(10)
);
--항공사 AIRLINE_RECYCLEBIN 시퀀스
DROP SEQUENCE AIRLINE_RECYCLEBIN_SEQ;
CREATE SEQUENCE AIRLINE_RECYCLEBIN_SEQ
START WITH 1
INCREMENT BY 1;

--항공사 AIRLINE DELETE TRIGGER
CREATE OR REPLACE TRIGGER AIRLINE_RECYCLEBIN_TRIGGER
    BEFORE DELETE ON AIRLINE
    FOR EACH ROW
BEGIN
    INSERT INTO AIRLINE_RECYCLEBIN VALUES(AIRLINE_RECYCLEBIN_SEQ.NEXTVAL,:OLD.NO, :OLD.NAME,:OLD.ENGLISH_NAME, :OLD.COUNTRY, :OLD.GRADE);
END;
/